import Image from "next/image";
import { cn } from "@/lib/utils";

export default function HindupediaContent({ isMarathi }: { isMarathi: boolean }) {
  const fontClass = isMarathi ? "font-mukta" : "font-cinzel tracking-wide";
  const pClass = cn("text-lg md:text-2xl leading-[2.2] text-[#cbbba0] text-justify", fontClass);
  const h2Class = cn("text-3xl md:text-4xl font-bold mt-16 mb-8 text-[#d4af37]", isMarathi ? "font-yatra" : "font-cinzel");
  const h3Class = cn("text-2xl md:text-3xl font-semibold mt-12 mb-6 text-[#d4af37]/80", isMarathi ? "font-yatra" : "font-cinzel");

  return (
    <div className="flex flex-col gap-8">
      <h1 className={cn("text-4xl md:text-6xl font-bold mb-8 text-[#d4af37] text-center drop-shadow-lg tracking-widest", isMarathi ? "font-yatra" : "font-cinzel")}>
        Vithoba of Pandharpur
      </h1>
      <p className="text-center text-[#cbbba0] opacity-80 mb-16 italic font-cinzel">By Dr Suruchi Pandey (Source: Hindupedia)</p>

      {/* Responsive image gallery — drop your reference images into public/images/ */}
      <section className="w-full max-w-6xl mx-auto px-4 md:px-0">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-start mb-8">
          <div className="md:col-span-2">
            <Image
              src="/images/panduranga-hero.jpg"
              alt="Panduranga sculpture"
              width={1200}
              height={800}
              className="rounded-lg object-cover w-full h-[420px] shadow-lg"
            />
            <p className="mt-2 text-sm text-[#cbbba0] italic">Sculptural panel from a Pandharpur temple (photo reference).</p>
          </div>

          <div className="flex flex-col gap-4">
            <Image
              src="/images/panduranga-2.jpg"
              alt="Temple sculpture detail"
              width={800}
              height={400}
              className="rounded-lg object-cover w-full h-[200px] shadow"
            />
            <Image
              src="/images/panduranga-3.jpg"
              alt="Temple base carving"
              width={800}
              height={400}
              className="rounded-lg object-cover w-full h-[200px] shadow"
            />
          </div>
        </div>
      </section>

      <p className={pClass}>
        <span className={cn("float-left text-7xl md:text-8xl mr-4 mt-2 text-[#8c6b42]", isMarathi ? "font-yatra" : "font-cinzel")}>P</span>
        andharpur is the abode of Sri Vitthala or Vithoba, who is the essence and synthesis of Vishnu and Krishna.
      </p>

      <p className={pClass}>Ashadhi Ekadashi is a day of great celebration and jubilation at Pandharpur, when the Varkaris—devotees of Vitthala who gather from all over Maharashtra, walking all the way from their homes to Pandharpur—have the holy darshan of their beloved deity. There is a massive influx of devotees, creating enormously crowded streets dotted with canvas tents for medical aid and vaccination.</p>

      <p className={pClass}>The road from Mohol to Pandharpur is lined with neem trees casting their reticulated shadows on the ground. They create a medicinal aroma and have yellow seeds that end up profusely scattered under the trees.</p>

      <p className={pClass}>The roads leading to the main temple of Vitthala are paved with cobblestones. Outside the temple were small shops selling thick garlands of tulsi leaves, kumkum, abir, bukka—used for the auspicious marks on the forehead, and sweets—peda, sugar candy, and the like. The air is often thick with the fragrance of tulsi. The whole atmosphere is charged with devotion, vibrant bhajans and kirtans are always ongoing, reverberating with the melodious beats of the dhol, pakhawaj, mridanga, tal, and chiplya (drums and cymbals).</p>

      <p className={pClass}>Pandharpur is full of temples. One of the most famous is the temple of Takpitya Vithoba (Vithoba who drinks buttermilk). Legend relates this deity to a simple woman devotee of yore. If for some reason she could not go to the main temple for darshan, she would offer a mixture of buttermilk (tak) and ground lahi (parched jowar, wheat, or paddy) as the naivedya (food offering) to Vitthala at her own home. And the deity, attracted by her ardent and pure devotion, would come to her house and relish the food. The shrine of Takpitya Vithoba was built by a brahmana widow named Radhabai in 1540 ce.[1] The temple still has the stone bowl that the devotee used for offering food.</p>

      <p className={pClass}>The Math of Kaikadi Maharaj is a great attraction for children at Pandharpur. It has lots of brightly colored images and paintings of various scenes based on Puranic descriptions. The pictures depicting the punishments supposed to be meted out to people in hell for their past wrongs are awe-inspiring and leave indelible impressions on the minds of children.</p>

      <p className={pClass}>Varkaris, devotees of Vitthala trek to see their very own vithai mauli (Mother Vithoba), putting up cheerfully with all the difficulties and inconveniences of a long journey. When we read Sant Jnaneshwar’s virahinis (philosophical poems dealing with the pangs of separation from God) or Sant Tukaram’s abhangas (a particular metrical composition in praise of the deity), we can feel the fervour and intense longing for the Supreme Presence. Jnaneshwar says, ‘pailatoge kau kokatahe, shakun ge maye sangatahe; the crow is calling on the other side, predicting some auspicious happening.’ He wishes to adorn the feet of this crow with gold, for it is telling that ‘Pandharirau (that is, Vitthala) would be coming home as a guest’. Tukaram says, ‘bhetilage jiva lagalise asa; the jiva is longing to meet you, O Lord.’ A remarkable intensity of emotion and agony—generated by the separation from Vitthala—is expressed through these simple but penetrating words. What, in reality, is the nature of Vitthala? For saints he is the rajasa and sukumara, handsome and youthful, giving rise to spiritual restlessness and passion in the very depths of the hearts of numerous devotees.</p>

      <p className={pClass}>Maharashtra has a unique tradition of bhajan explified by the forceful melody of Pandit Bhimsen Joshi’s abhangavani or Lata Mangeshkar's renditions of Tukaram's abhangas.</p>

      <h2 className={h2Class}>Pandharpur: The Holy City</h2>
      <p className={pClass}>The principle deity of Pandharpur is Sri Vitthala. The chief priests are from the Badve family. The front portion of the temple of Vitthala is known as gad, fortress. The temple has three doors each on its eastern and northern sides, and a door each on the south and west. The main door on the eastern side is the one frequently used, so it is called the Mahadwara. It is also called Namdev Darwaja, Namdev’s door. Near the Mahadwara, there is the samadhi-pitha (memorial) of the saint Chokhoba. We have to climb twelve steps to reach it. The first of these steps is known as Namdevchi Payari (Namdev’s step). Sant Namdev left his mortal coil at this very place. A brass image of his face is installed here. Namdev firmly believed that if he were to receive the touch of the ardent devotees of Vitthala, he would certainly be liberated. This step is sacred to the devotees. They take care not to step on it.</p>
      
      <p className={pClass}>The temple begins with the mandap (porch) that serves as the nagar-khana, room for the drums and other instruments of the temple band. Next is the chowk or the temple courtyard. The chowk is lined with several owaris, rooms meant for accommodating pilgrims and resident devotees. The owaris have been framed in wood by the Badve family. The samadhi-pithas of Sadhu Prahladabua Badve and Kanhaya Haridas can be seen here. To the west of the mandap are two dipamalas—stone pillars for lamps lit on festive occasions. The wooden mandap also has a small shrine each to Garuda and Maruti Hanuman. The Hanuman image was installed by Samarth Ramdas.</p>

      <p className={pClass}>Next are the images of Jaya and Vijaya— deities who protect the temple—and reach the Solakhambi Mandap (sixteen-pillared hall). Scenes from the Krishna-lila, images of Matsya, Kurma, and other avataras, and decorative floral designs are carved on these pillars. According to researchers this mandap was constructed in the Muslim era. The Garuda-khamb, covered with gold and silver plates, is the important pillar here. Garuda is the vehicle of Bhagavan Vishnu. He is a great devotee. So the devotees embrace this pillar lovingly and then move onwards for darshan of Vitthala. The entrance to the shrine is to the west, through the door known as Rupyacha Darwaja (the silver door). On crossing this door we reach the Chowkhambi Mandap (the four-pillared porch). The Hatti Darwaja (elephant door) with carved elephants on both sides is to the south. The image of Vithoba is three and a half feet tall and bears a shivalinga on the head. Around his neck, Vitthala has the kaustubha-mani (a precious gem that was obtained during the mythical churning of the ocean) and his breast is adorned with the footmark of his devotee, known as vatsalanchhana. The backdrop of the image is formed by a prabhaval, a decorative silver plate.</p>

      <p className={pClass}>The image of the saint woman Kanhopatra can be seen in a niche on the wall if the temple is entered from its southern door. Behind the Vitthala shrine, to the northwest, is the shrine to Rukmini, the consort of Vitthala. The shrines to Satyabhama and Rahi are also close by.</p>

      <p className={pClass}>One particularly unique feature of the temple is that Rakhumai (the popular name of Rukmini) and Vithoba have separate shrines. There is a story among the Dhangars—who have traditionally been shepherds, herdsmen, and wool weavers—regarding this permanent parting.</p>

      <p className={pClass}>Vithoba’s wife actually had the name Padmavati and she was fondly called Padubai. She always had to remain busy with her household chores. Once she was extremely tired and so refused to serve Maliraya, a guest of her husband. Vithoba turned furious and pronounced a curse that she would go mad and be separated from him. Vithoba’s curse came true. Padubai went to the forest and died under a tamarind tree. Her parents Janakoji and Kamalaja ran to see her when they heard of this sad turn of events. But Vithoba assumed the form of a snake and sat blocking the way. He would not allow anyone to go near Padubai’s corpse, even as kites and vultures ate it up. He then had clouds pour showers and wash Padubai’s bones to the sea. This tragedy badly upset Maliraya as he felt he had caused it. So he undertook penance by the seashore for the next twelve years. The sea was pleased with his tapas and Maliraya requested the sea to return Padubai’s bones. He then reverentially immersed these bones in Padmatirtha, a lake by the Chandrabhaga River, and a beautiful lotus emerged from its waters. Meanwhile, Vithoba was tormented by the separation from Padubai. He was wandering restlessly in search of Padubai when he reached the shores of Padmatirtha and saw the beautiful lotus. He plucked it, and lo! Padubai appeared before him bearing the name Rukmini. But Vithoba had by now got over his attachment for samsara. He said, ‘My words cannot be untrue. Our household life has come to an end. We shall not be under one roof. But we shall meet every day, communicate with each other, and dedicate our lives to the welfare of our devotees.’</p>

      <p className={pClass}>This story has a symbolic meaning. Vithoba is the symbol of non-attachment; he is portrayed as the conqueror of kamini and kanchana. Together, Vithoba and Rukmini represent humans with divine qualities. So they accepted their suffering and a life of duty, devotion, forgiveness, and truth. They decided to live for the sake of their devotees.</p>

      <p className={pClass}>Satyabhama is the wife of Krishna and Radha is his dear friend. Rahi is Radha. In the stories and legends of Maharashtra, Rahi is the wife of Vitthala.</p>

      <p className={pClass}>Besides these main temples there are the images of Kashi Vishwanatha, Rama-Lakshmana, Kalabhairava, Rameshwara Shiva, Dattatreya, and Narsoba in six different rooms. A seventh room lies vacant. These rooms were built by Kanbawa Badve. There is a narrow walk between these rooms and the Solakhambi Mandap. At the eastern end of this walk, there is a piece of inscription known as Chauryanshicha Shilalekh (the stone inscription of eighty-four).</p>

      <p className={pClass}>There are numerous other temples at Pandharpur. These include the temples to: Takpitya Vithoba, Pundalika, Vishnupada-Venunada, Gopalakrishna of Gopalpur, and Muralidhara; Gondavalekar Rama; Mallikarjuna, Bhuleshwara, Tryambakeshwara, Koteshwara, Vateshwara, and Amriteshwara; Nagareshwara Sarkarvada Mahadeva, Bhadalyacha Mahadeva, Garecha Mahadeva, and Bericha Mahadeva; Ganapati, Shakambhari, Chandrabhaga, and Paravaril Datta; Panchamukhi Maruti, Tambada Maruti, and Kala Maruti; Khajgivale Murti; Padmavati, Vyasa, Ambabai, Lakhubai, Yamai and Jyotiba, and Namdev. There is also the samadhi-pitha of Sridhara Swami and Mahaprabhuchi Baithak (Mahaprabhu’s parlour).</p>

      <h2 className={h2Class}>Vithoba’s Image</h2>
      <p className={pClass}>Researchers hold varying opinions about the history of the Vitthala temple and image. The main temple was built by the Yadavas of Devagiri in the twelfth century, though the deity was well-known several centuries earlier. During the Muslim invasion in the sixteenth century, the image had to be kept hidden for fear of desecration.</p>

      <p className={pClass}>Researchers debate whether Vitthala is a Karnataki or Kannada deity rather than a Marathi deity. Jnaneshwar says: ‘kanada ho vitthalu karnataku, yene maja lavile vedhi; this Vitthala who is kanada (difficult to understand) and karnataku (from Karnataka, or kara nataku, playful) has put me in the state of constant remembrance.’ Saints like Eknath and Namdev have also referred to him as kanada vitthala. Those who vouch for his being Marathi emphasize that kanada means ‘inaccessible, indescribable’. [3]</p>

      <p className={pClass}>Geographically, Pandharpur is on the border of Maharashtra and Karnataka. The ancient name of Pandharpur was Pandarage.</p>

      <p className={pClass}>To the saints, there is no point in such regionalism. All of them bear a tender affection and innocent love for Vitthala. For them, Vitthala is ‘savaleparabrahma; Para-brahman with a dark complexion’; he is Hari in the form of a gopa (cowherd); he is also Shiva and Vishnu. There are many Kannada saints and poets who have sung the glory of Vitthala with loving devotion. In his poem ‘Pandurangamahatmyamu’, the Telugu poet Tenali Ramakrishna too sings praises to Vitthala:</p>

      <p className={pClass}>Pundarikundu kshetrapalundu golichi yunda navyaktamukhya samyuktundaguchu pandurangandu bhaktakalpadrulila nishthaphalasiddhi dorahattinchu ninti</p>
      
      <p className={pClass}>(O Parvati), accepting the services of Pundarika and Kshetrapala (Kala-bhairava), becoming the wish fulfilling tree by assuming a subtle body for the sake of devotees, fulfilling their wishes, the deity Panduranga resides in that temple.</p>

      <p className={pClass}>This shows that Vitthala is an impressive symbol of synthesis. He became the center for the emergence of a unique social and spiritual movement. The devotee saints declared war against hollow rituals and hypocrisy. They were not interested in the shallow vulgar show of erudition. On the contrary they wanted to experience the spirit of the ‘one without a second’ in their own life. Why do we need temples? Because temples and deities represent humbleness which, along with goodness and the spirit of synthesis, we need to protect. If this purpose is not served, then sacred places and temples are mere heaps of stone. Tukaram says: ‘tirthi dhondapani, deva rokada sajjani; holy places are made of mere stones, God is in wisdom and in the pious’.</p>

      <h2 className={h2Class}>Vithoba, Vitthala, Panduranga</h2>
      <p className={pClass}>The Varkaris fondly address Vitthala as Vithoba Mauli (Mother Vithoba). According to legend he is related to both Shiva and Vishnu. Panduranga is another of his popular names. Scholars have provided interesting insights into the etymological meanings of these names. [4]</p>

      <p className={pClass}>If the image of Vitthala is black, why is he called Panduranga (white coloured)? R C Dhere has pointed out that though the Skanda Purana mentions ‘Panduranga’ as a synonym for ‘Vitthala’; it is actually the name of the holy site of Vitthala’s shrine. Just as ‘Kashi Vishwanatha’ means ‘Vishwanatha of Kashi’, ‘Panduranga Vitthala’ means ‘Vitthala of Panduranga’. [5] According to the Deshinamamala of Hemachandra (c. 11th cent. ce) the deity is Pandarango Ruddammi and is related to Rudra-Shiva. A copper plate dated 516 ce records the grant of five villages (or towns) to the brahmana Jayadvittha by the Rashtrakuta king Avidheya. One of these five villages is Pandarangapalli. Similarly, there is the Sanskrit-Kannada inscription (1236 ce) carved on a beam in the Solakhambi Mandap of the main temple of Vitthala where Pandharpur is referred to as Pandaranga.</p>

      <p className={pClass}>In a copper plate found at Bendigere near Belgaum, Pandharpur is referred to as Paundarika Kshetra and Vitthala is described as Vishnu. Elsewhere, Pandharpur is called Phagnipur. In the Jnaneshwari, King Ramadevarai Yadava is described as ‘pandhari-phada-mukhya’. Pandhari refers to the tutelary village god and phada is a place of public business. So Ramadevarai was the chief of the business centre Pandharpur.</p>

      <p className={pClass}>Several etymological derivations have been suggested for the term vitthala. The deity stood and waited on a brick (vit in Marathi) thrown by his great devotee Pundarika; so he is Vitthala. Vishatara means a darbhasana (a grass seat) and vishatala a remote place. So one who lives in such a place is Vitthala (the letters ra and la are often exchanged in Prakrit languages).</p>

      <p className={pClass}>Tukaram says, ‘vicha kela thoba, mhanoni nav to vithoba; the learned say that Vitthala is one who is gracious towards innocent people devoid of knowledge.’ A more esoteric explanation is as follows: vit means knowledge, and tha means shunya (void); so vittha signifies ignorance and the suffix la ‘one who accepts’. So Vitthala is the one who protects ignorant jivas. Or, as he is all-pervasive, resides in akasha or viyat-sthala (space), and is absorbed into akasha, he is Vitthala.</p>

      <p className={pClass}>In contrast to the above explanations, there is a general agreement among linguists that the word vitthala is related to the Prakrit for Vishnu, vittha (vishnu → vishtu → bitthu → vitthulu → vitthalu → vitthala). Rakhumai is Vitthala’s spiritual consort. This name is derived from Lakshmi (lakshmi → lakshma → lakhama → rakhama → rakhuma). If Vishnu is Vitthala, his spouse must be Lakshmi or Rakhumai.</p>

      <p className={pClass}>But to the simple-hearted Varkari devotees, these analytical details are not of much interest. To them Vitthala is their mother, Vithoba Mauli.</p>

      <p className={pClass}>References to Pandharpur and Vitthala are found in the Puranas, in the abhangas (hymns) of the saints, in stone inscriptions, and in popular literature.</p>

      <h2 className={h2Class}>Early References to Pandharpur and Vitthala</h2>
      <p className={pClass}>Puranic Sources • The sthalamahatmyas (chapters on ‘greatness of sacred sites’) in the Puranas contain a wealth of fable, legend, and historical information as well as reflections on ancient traditions and indigenous culture.</p>

      <p className={pClass}>The Skanda and Padma Puranas refer to places known as Panduranga-kshetra and Pundarikakshetra or Paundarika-kshetra. The Padma Purana also mentions Dindiravana, Lohadanda-kshetra, Lakshmi-tirtha, and Mallikarjuna-vana, names that are associated with Pandharpur. There are mythical tales connected to these popular names. For instance, the Dindiravana forest was so named because it was associated with the demon Dindirava. When his arrogance crossed all limits, Vishnu took the form of Mallikarjuna Shiva and put him to death with an iron rod, lohadanda.</p>

      <p className={pClass}>Again, when Krishna started showing greater affection for Radha, Rukmini was displeased, and leaving Krishna in Dwaraka, she went away to Dindiravana on the River Bhima. In order to pacify her, Krishna came to Dindiravana with his cowherd companions, the gopas. They camped at Gopalpur while Krishna went to meet Rukmini. So the Gopalakrishna of Gopalpur is an important deity even today. While he was looking for Rukmini, Krishna also met the famous devotee Pundalika.</p>

      <p className={pClass}>Another legend tells of the beautiful Padma who was performing hard penance to get a suitable husband. Satisfied with her tapas, the Deity appeared before her in a very handsome form. Seeing him, Padma lost consciousness, her hair all-disheveled (muktakeshi). Her wish was granted and the place of her tapas became ‘Kshetra Muktakeshi’.</p>

      <p className={pClass}>There are stories related to the names of various places in the Pandharpur Kshetra. These are also attempts at synthesizing the cults of Shiva and Vishnu or the Sri Venkatesha and Sri Vitthala form of Vishnu. It is interesting to note that Venkatesha and Vitthala do not have any prominent place in the Puranas, but they are extremely popular deities. And there are interesting parallels in their tradition. Vitthala is adored in his balarupa (child form) and Venkatesha is balaji. [7] Both their consorts stay apart. Padmavati, Venkatesha’s wife, was displeased with her husband for tolerating Bhrigu’s insult. So she went away, first to Karavira and then to Tiruchanur, three miles away from Tirumalai, where Venkatesha resides. Both Venkatesha and Vitthala do not carry any weapons. Some of the images of these deities obtained from archaeological excavations also show similarities. Both the icons are katinyasta kara (having their hands on their waist). The Pandurangashataka by Sri Shankaracharya explains the reason:</p>

      <p className={pClass}>Pramanam bhavabdheridam mamakanam Nitambah karabhyam dhrito yena tasmat Vidhaturvasatyaihi dhrito nabhikoshah Parabrahmalingam bhaje pandurangam</p>
      
      <p className={pClass}>I pray to the Panduranga, the representation of Para-brahman, who rested his hands on his waist to show his devotees the depth of the ocean of samsara, and who holds a (lotus) bud in his navel for Vidhata (Brahma) to stay. [8]</p>

      <h3 className={h3Class}>Stone Inscriptions</h3>
      <p className={pClass}>The beam on the eastern door of the Solakhambi Mandap bears a Sanskrit-Kannada inscription (c. 12th cent. ce) written in Devanagari, which says that the Hoyasala Yadava Vir Someshwara donated the land of Hiriyaganja for the service—angabhoga and rangabhoga of Sri Vitthala. The Chauryanshicha Shilalekha is another famous inscription. Chauryanshi is eighty-four in Marathi. It is believed that rubbing one’s back on the surface of this stone inscription provides liberation from eighty-four lakh births. Experts believe that this inscription can be dated to seventeen years before the composition of the Jnaneshwari text (c. 1290 ce). Another inscription from Hebbali near Dharwad—dated to 1248 ce—bears the phrase ‘Sri Pandurangeya Sri Vitthaladevara’. [9]</p>

      <p className={pClass}>It can be reasonably inferred from historical records that Vitthala and Pandharpur started gaining widespread popularity and loving acceptance among the masses after the 6th cent ce. A copperplate inscription of that period mentions Pandharpur as a palli (small village), while in the inscription of the Hoyasalas it is a mahagrama (big village or town). This transition is suggestive of the growth of devotion to Vitthala.</p>

      <h2 className={h2Class}>The Meaning of ‘Varkari‘</h2>
      <p className={pClass}>Every Maharashtrian is familiar with the term ‘Varkari’. It brings to mind a characteristic image: a person dressed in dhoti and uparane (a small piece of cloth worn loosely round the shoulders), with bukka on the forehead, a rosary of tulsi beads round the neck, tal (cymbals) in hand, a saffron flag on the shoulder, continuously repeating ‘ramakrishna hari’. A Varkari is one who religiously performs the vari (pilgrimage) to Pandharpur on foot, especially during the months of Ashadha (mid June to mid July) and Kartika (mid October to mid November). Many people go on pilgrimages, but the term ‘Varkari’ has got exclusively associated with the pilgrimage to Pandharpur. The term not only suggests a specific appearance, it also suggests the espousal of a particular philosophy and a certain way of life. The Varkari sampradaya (tradition) has also produced a succession of distinguished and elevated saints.</p>

      <p className={pClass}>One who goes to Pandharpur on a vari is a Varikar or Varkari. There are several opinions about the origin of the term. According to Sri Rajvade vari means a group or a mass of particulars or individuals (2). The Amarakosha mentions vara as synonymous with sanghata and samudaya (that is, a group) as well as avasara, opportune time. [10] The Jnaneshwari also mentions vari:</p>
      
      <p className={pClass}>Yachi ekepari, rupakachiya kusari; Saritase vari, samsarachi.</p>

      <p className={pClass}>From this (simile of a tree), the Lord has skillfully shown the futility of the world and has given a way out of the cycle of birth and death. [11]</p>

      <p className={pClass}>Aise vairagya he kari, tari sankalpachi sare vari; Sukhe dhriticha dhavalari, buddhi nande.</p>

      <p className={pClass}>When thus dispassion is achieved the resolve [for enjoyment] becomes power less, the seeker gets courage and the pure intellect starts working [12].</p>

      <p className={pClass}>Here the word vari means ‘a trip, rounds, or going about’. [13] According to Molesworth’s Marathi-English Dictionary, vari means ‘the practice of proceeding regularly at recurring monthly or annual periods on pilgrimage to any sacred place’. The practices of various saints and devotees have given ‘Varkari’ its current meaning ‘the ritual pilgrimage to Pandharpur’. In every village and in every city of Maharashtra we find people who proudly call themselves Varkaris.</p>

      <p className={pClass}>The Varkari sampradaya is also called the Malkari or Bhagavata sampradaya. Why are Varkaris called Malkaris? This is because they wear a rosary of tulsi beads, and tulsi is dear to Vitthala. This rosary is the symbol of a life dedicated to Vitthala. One who offers everything to Bhagavan is a bhagavata. The term suggests a preponderance of bhakti, devotion. The Eknathi Bhagavata text says:</p>

      <p className={pClass}>Dara sutagrihaprana karave bhagavantasi arpana; He bhagvatadharma purna mukhyatvebhajan ya nava.</p>

      <p className={pClass}>The true sense of the Bhagavata religion is in dedication of one’s wife, children, home, and life to Bhagavan. Bhajan is the name (main feature) of this (dharma). [14]</p>

      <p className={pClass}>Having dedicated themselves to God, the Varikaras are naturally generous:</p>

      <p className={pClass}>Kaya vacha mane jive sarvasve udara; Bapa rakhumadevi-vara vitthalacha varikara.</p>

      <p className={pClass}>The Varikara, whose father is Vitthala—the husband of Rakhumadevi—is generous with all of his body, speech, mind, and life. [15]</p>

      <h2 className={h2Class}>The Varkari Code of Conduct</h2>
      <p className={pClass}>The Varkaris follow the tradition of vari to Pandharpur. There is also a tradition of vari to Alandi, the birthplace of Jnaneshwar. Ashadha Shuddha Ekadashi is the important day at Pandharpur and Kartika Vadya Ekadashi at Alandi. During the vari to both these places, bhajans are sung from dashami (the tenth day of the fortnight) to purnima or amavasya (the full- and new-moon days). On purnima, all dindis (groups) involved in the vari go to Gopalpur near Pandharpur. The ceremony of offering kala (parched grains of jowar mixed with curd) is performed here. All the Varkaris partake of this kala as pious prasad and here ends their holy journey.</p>

      <p className={pClass}>The Varkari families follow the tradition of vari with love and devotion from generation to generation. With exalted minds they walk tirelessly to Pandharpur, unmindful of scorching heat or pouring rain. Jnaneshwar and Namdev have beautifully described the congregation of these Varkaris. Jnaneshwar says:</p>

      <p className={pClass}>Anande preme garjati bhadrajati vitthalache; Tulasimala shobhati kanthi gopichandanachi uti. Aise ekangavira vitthalarayache dingara; Baparakhumadevivara jihi nirdhari jodala.</p>

      <p className={pClass}>(These Varkaris), adorned with tulsi garland round their necks and sandal-paste on their forehead, announce the (name of the) pious Vitthala. Staunch followers, brave men, they are the children of Vitthalaraya. They have united themselves firmly to their father Vitthala, the consort of Rakhumadevi (ibid.).</p>

      <p className={pClass}>Namdev who was contemporaneous with Jnaneshwar says:</p>

      <p className={pClass}>Ale ale re hariche dingara Vira varikar pandhariche; Bhakti premabhava bharale jyanchya angi Nachati harirangi nenati laju.</p>

      <p className={pClass}>Here come the children of Hari, the brave Varikaras of Pandharpur, whose being is full of devotion and love. Coloured by Hari, they dance without reserve (5).</p>

      <p className={pClass}>It is interesting to note that though the Bhagavata sampradaya emphasizes bhakti, the forms of its upasana (spiritual practices) tend towards Advaita. Though in their works Jnaneshwar and Namdev speak of ‘krishnamurti savali; the black image of Krishna’, or say, ‘hridayi krishnamurti bheto ali; the image of Krishna came to meet me deep in my heart’, the magnificent concept of ‘vishvakara harirupa; the cosmic form of Hari’ finds repeated expression in the compositions of the Varkari saints.</p>

      <p className={pClass}>Wearing a rosary of tulsi beads is of utmost importance to the Varkaris. Vitthala is the child (balasvarupa) Krishna. The tulsi plant is dear to Krishna. So a Varikara must wear a rosary containing a hundred and eight tulsi beads as a pious observance. If the thread of the rosary happens to snap, the staunch Varikara would not have food until the rosary is repaired. There is a touching story about tulsi among the Kunbis (an agricultural community) in Maharashtra. It goes like this: Tulsi was the daughter of a poor brahmana. She had a dark complexion and a brahmana husband was not in her fate. Due to poverty, her hapless father deserted her. The gavali (cowherd) Vithoba offered refuge to orphaned Tulsi. But Rukmini was not happy with Vitthala’s overtures. Rukmini’s attitude hurt Tulsi and she decided to take shelter with Mother Earth. As she was disappearing in the bosom of the earth, Vithoba hurriedly pulled her out. But instead of Tulsi, the holy basil (tulsi) came into his hands. Vithoba had promised to marry Tulsi. He kept his words by marrying the holy basil. This is the reason why Vithoba always has a garland of tulsi around his neck.</p>

      <p className={pClass}>The rosary keeps the Varkaris alert about their ideals right up to the end of their lives. Sandal-paste (gopi-chandan) and black-powder (bukka) marks on the forehead, and the saffron flag carried on the shoulder are the other important components of their insignia. There are certain moral and ethical precepts that every Varkari is to follow:</p>
      
      <ul className={cn("list-disc pl-8 space-y-2", pClass)}>
        <li>Adherence to truth.</li>
        <li>Treating all women other than one’s own wife as Rakhumai (Mother Rukmini).</li>
        <li>Confessing unintentional transgressions to Bhagavan and praying for his forgiveness.</li>
        <li>Being a vegetarian.</li>
        <li>Visiting Pandharpur and Alandi at least once a year.</li>
        <li>Observance of ekadashi fasts.</li>
        <li>Japa of one’s mantra at least a hundred and eight times every day.</li>
        <li>Daily study and contemplation of such texts as the Jnaneshwari and Haripatha.</li>
        <li>Performing all household duties with compassion but non-attachment, maintaining the awareness of Vitthala.</li>
      </ul>

      <p className={pClass}>The Varkari philosophy advises devotees to face miseries and hindrances with courage and firmness of mind and rise above samsara. No work is futile. We get our share of work because God wishes it to be so. We should work keeping in mind that it is our pious duty to do so and that we are answerable to God. The Varkaris are divided into several subsects, each having its own mantra:</p>
      
      <ul className={cn("list-disc pl-8 space-y-2", pClass)}>
        <li>Chaitanya Sampradaya: It has two divisions; one group repeats the mantra ‘ramakrishna hari’, while the other repeats ‘om namo bhagavate vasudevaya’.</li>
        <li>Swarupa Sampradaya: Their mantra is ‘sriram jaya ram jaya jaya ram’. This sampradaya has two divisions—the Ramanuji and the Ramanandi.</li>
        <li>Ananda Sampradaya: The followers of this sampradaya repeat the name ‘sriram’ or ‘ram’.</li>
        <li>Prakasha Sampradaya: Members of this sampradaya chant the mantra ‘om namo narayanaya’. [16]</li>
      </ul>

      <h2 className={h2Class}>History of the Varkari Sampradaya</h2>
      <p className={pClass}>It is convenient to divide the history of the Varkari sampradaya into five phases:</p>
      <ul className={cn("list-decimal pl-8 space-y-2", pClass)}>
        <li>From Pundalika to Jnaneshwar</li>
        <li>From Jnaneshwar to Namdev</li>
        <li>The period of Bhanudas and Eknath</li>
        <li>The Tukaram period</li>
        <li>The post-Tukaram period</li>
      </ul>

      <h3 className={h3Class}>From Pundalika to Jnaneshwar</h3>
      <p className={pClass}>The exact time of the devotee Pundalika (or Pundarika) is uncertain. The Padma Purana and the Skanda Purana tell the story of Pundalika. Pundalika was an ordinary man madly in love with his wife. Due to this inordinate attachment he tended to neglect his own aged parents. Eventually, he met Kukkuta Swami and underwent a radical transformation; service to parents became his foremost priority.</p>
      <p className={pClass}>Another story goes like this: When Vitthala was searching for Rukmini in the Dindiravana forest, he happened to chance upon Pundalika’s house. Pundalika was busy serving his parents. So he provided a brick for Vitthala to rest on. Vitthala stood on the brick and waited patiently for his devotee. After completing his services, Pundalika prayed to Vitthala and sang his glories. The deity was pleased and he asked Pundalika what he desired most. Pundalika requested Vitthala ‘to stay here permanently and lift jivas from ignorance’. Vitthala happily assented to the loving demands of his devotee. Hence the place came to be known as Pundarikapur.</p>
      <p className={pClass}>There is no unanimity about the period of the Puranas. So it is difficult to ascertain when Pundalika lived. It can be inferred from epigraphic evidence that at least half a century before the time of Jnaneshwar people knew a sage called Pundalika Muni. The Panduranga-shataka-stotra composed by Sri Shankaracharya refers to Pundalika. Sri Shankaracharya is generally believed to have flourished around the 8th cent. ce. It follows that Pundalika and Vitthala were well-known by this time. The Rashtrakuta copperplate inscription of 516 ce mentioned earlier also refers to the temple of Vitthala.</p>
      <p className={pClass}>In his book Malutaran, Narahari Dhundiraj Malu suggests that King Shalivahana, who is reputed to have initiated the Shaka era, established the town of Pandharpur, placing it under the charge of his chief minister Ramachandra Sonar. The forest of Dindiravana was cleared to erect the temple of Panduranga and a few other temples. This text does not appear to be backed by adequate historical evidence; but if there is any truth in it, then the legend of Pundalika and the temple of Vitthala goes back to the 1st cent. ce. [17]</p>
      <p className={pClass}>It is, however, indisputable that the Vitthalabhakti cult was well established by the 6th cent ce. After this period the cult underwent remarkable growth and spread. There is no specific reference clarifying the origin of the vari tradition. But there were people who followed the tradition of vari to Pandharpur well before the time of Jnaneshwar. Namdev says that Vitthalapant, Jnaneshwar’s father, did the Ashadhi and Kartiki varis. People used to come for the darshan of Vitthala from all over Maharashtra, Telangana, and Karnataka at this time.</p>

      <h3 className={h3Class}>From Jnaneshwar (1275–1296) to Namdev (1270?–1350?)</h3>
      <p className={pClass}>Though the Varkari tradition had originated before their time, Jnaneshwar and Namdev provided it with a firm foundation and a unique philosophy. Jnaneshwar was the major source of inspiration. The Natha tradition, into which Jnaneshwar was initiated by his brother Nivrittinatha, is primarily concerned with yoga. But we notice the intimacy of devotion in the writings of both the brothers. Even their father’s name, Vitthalapant, suggests that there was a tradition of Vitthala-bhakti in the family.</p>
      <p className={pClass}>Vitthalapant had taken sannyasa some time after his marriage to Rakhumai. When his teacher Ramananda came to know that he had done so without the consent of his wife, he ordered Vitthalapant to go back and reassume the householder’s life. Vitthalapant complied with his teacher’s command and had four children: Nivritti, Jnanadeva, Sopana, and the daughter Muktabai. To the local brahmana community and the scholars, Vitthalapant’s abdication of sannyasa was sacrilegious. The whole family was excommunicated from society. The couple decided to end their lives by way of expiation so that their children would not have to face injustice and torture.</p>
      <p className={pClass}>Jnanadeva had to go to Paithan to get a shuddhipatra (certificate of purification through expiation, prayashchitta) from the learned brahmanas of that town. This was in 1290. While returning from Paithan, Jnanadeva halted at the village Nevase. Sitting besides a pillar in the local Shiva temple he composed his exquisite commentary on the Bhagavadgita called Bhavartha-dipika or Jnaneshwari. It has no equal in Marathi literature. The text provides the Varkari order its tranquil philosophy. Having experienced grave social injustice, Jnaneshwar was quick to apprehend that none in society was keen on understanding the real essence of religion; external bustle and ostentatious display seemed more important. So he was eager to convey the proper meaning of religious philosophy and show its application to everyday life.</p>
      <p className={pClass}>Jnaneshwar propounds the theory of chid-vilasa-vada. If we presume chaitanya, universal consciousness, to be the only truth, then whatever is seen or experienced becomes false, mithya, in the ultimate analysis. This view, stretched to the extreme, can lead to complete nihilism. The theory of chid-vilasa-vada avoids such extremes.</p>
      <p className={pClass}>According to chid-vilasa-vada, chaitanya is inseparable from energy, and the universe, vishwa, is its manifestation or play, vilasa. The term ‘maya’ also suggests a sort of play, but this play is for God or Ishwara to enjoy. Jnaneshwar believes ‘brahma satya; Brahman is Truth’ and ‘jivo brahmaiva naparah; the individual soul is none other than Brahman’. But he lays greater emphasis on ‘sarvam khalvidam brahma; all this is indeed Brahman’ than on the intricacies of the doctrine of maya. He does not call this world abhasa or appearance. He prefers such examples as gold and golden ornaments, water and its waves, fabric and its fibres to explain the unity underlying diversity. He does not cite the examples of the ‘rope and the snake’, rajju-sarpa, where the snake is illusory. Jnaneshwar knew that the paths of yoga and jnana were difficult for ordinary people. So he introduced the comparatively easier path of knowledge combined with devotion. According to R K Bhagwat: ‘Although Jnāndev was mainly a follower of the Path of Yoga, he was also a follower of the Path of Devotion and also a “Vaishnava”, a follower of the fourfold caste system. With all this, it seems strange that absolutely no reference was made to God Vithobā of Pandharpur in the whole of Bhāvārthadīpikā, although there is an indirect reference to that God in that, Lord Krishna says that he holds on his head God Shankar, his great devotee.’ [18]</p>
      <p className={pClass}>Sri Bhagwat adds another hint: ‘It seems that through his association with Nāmdev, Jnāndev got admitted into the Vārkarī sect of devotees, the leadership of which also soon devolved on him’ (ibid.). Thus the later compositions of Jnaneshwar also proved useful in the development of the philosophy of the Varkari sect.</p>
      <p className={pClass}>Jnaneshwar’s was the period of the Yadava dynasty. The Jnaneshwari records:</p>
      <p className={pClass}>Tetha yaduvamshavilasu je sakalakala nivasu; Nyayati poshi kshitishu shriramachandra.</p>
      <p className={pClass}>There (reigns) the just protector of the earth—Sri Ramachandra of the Yadava dynasty, the very abode of all arts. [19]</p>
      <p className={pClass}>According to Professor Vafgaonkar, ‘Jnanesvari was written in 1290 ad. Ramdeva had freed Kashi from the clutches of Yavanas three or four years before this and had built the temple of Sharngadhara. And when Jnanesvari was being written, Ramdeva ruled Kashi. Perhaps because of the victory of Ramdeva and freeing of mlecchakranta Kashi, Jnanesvara honoured him in the Jnanesvari. … Even in the temple of Panduranga the inscription of Chauryanshicha Shilalekha, the king Ramdevaraya was called as the Pandhari-phada-mukhya.’ [20] It should be noted that this was the period when society was governed by karma-kanda or rituals prescribed in the Smritis, as is evidenced by the composition of Chaturvarga-chintamani by Hemadri (a minister of Ramadeva’s) at this time. Several incidents in Jnaneshwar’s life prove that varnashrama rules (of caste and station in life) were strictly being enforced. The upper castes and the untouchables were both affected by the rigidity of the caste system. The tender heart of the saint-poet was pained by the hypocrisy, sectarianism, and tyranny of the orthodox. His commentary on the Gita emphasizes the development of universality of consciousness and outlook by announcing that God’s gates are open to all without any distinction of caste, creed, or sex. He preached the Bhagavata Dharma of devotion to the Divine that underlies universal religion.</p>
      <p className={pClass}>Jnaneshwar went on long pilgrimages to far off places in northern India in the company of Namdev. Both of them spread far and wide the tenets of true religion coloured with devotion and compassion. Jnaneshwar ended his sojourn on earth by voluntarily choosing to be buried alive while in samadhi—jivanta samadhi—in the presence of his brothers, sister, and other saints. He was only twenty-one then.</p>
      <p className={pClass}>Namdev has his own singular contributions to the developments of the Varkari sampradaya. He went to stay at Ghuman near Amritsar, established a tradition of Vitthala-bhakti, and popularized the teachings of the Bhagavata Dharma through his forceful kirtans composed in the emerging Hindi. Ghuman is known as namdevki ghomani, Namdev’s Ghuman. The saffron flag flying in front of the memorial temple at Namdev’s math is called Jhandasahib Sri Namdevji. Among Namdev’s disciples were Vishnuswami, Bohardas, Jallo Sutar, Laddha Khatri, and Keso Kalasdhari. [21]The Delhi sultans ruled over North India at this time. It was in times of much political turmoil that Namdev accomplished his work. While compiling the Adi Granth, Guru Arjun included sixty-one of Namdev’s hymns. In one of these, Namdev says: ‘Ibhai bithalu, ubhai bithalu, bithala binu samsar nahi;Vitthala is here, Vitthala is there, without Vitthala the world is not.’</p>
      <p className={pClass}>Namdev wished that his body be kept near the Panduranga temple steps so that devotees would touch him with their holy feet while entering the temple. The Namdevchi Payari fulfils this wish symbolically. When the dindis (group of Varkaris) come near this step, they sing one of his abhangas:</p>
      <p className={pClass}>Sadhusanta sharan jau jivebhave Prasada svabhave deti gheti; Nama mhane amhi payariche chire Santa paya hire var deti</p>
      <p className={pClass}>We take complete refuge in saints. They will shower grace according to their very (compassionate) nature. Namdev says that we are hewn and shaped stones which holy saints step on.</p>
      <p className={pClass}>The efforts of Jnaneshwar and Namdev were particularly momentous because they emphatically enunciated that the doors of the Bhagavata religion were open to all. This period is significant in view of the works of a galaxy of saints from all sections of society. These included brahmanas like Nivrittinatha, Sopanadeva, Muktabai, Visoba Khechara, and Parisa Bhagavata, the potter Goroba, the gardener Savatoba, Kanhopatra—the daughter of a prostitute—the maid servant Janabai, the cobbler Rohidasa, the goldsmith Narahari, the barber Sena, and other saints from the lower classes like Chokhoba, Raka, and Banka. All of them were dazzling jewels in the social movement of the Varkari sampradaya. All of them practised religion in their own lives and tried to discover the expression and manifestation of their deity in their own work or profession. They avoided scholastic discussions about Brahman but boldly addressed vexed social issues. Chokhoba announced: ‘Harinama garjatabhaya nahi chitta; repeating the name of Hari, the mind knows no fear.’</p>

      <h3 className={h3Class}>The Period of Bhanudas (1448–1513) and Eknath (1533–99)</h3>
      <p className={pClass}>It is traditionally believed that King Krishnadeva Raya of Vijayanagar had the image of Panduranga taken to Hampi, possibly to prevent desecration by Muslim invaders. The absence of the deity sent the whole of Pandharpur into a pall of gloom. It was Paithankar Bhanudas Maharaj who brought back the deity to Pandharpur. Bhanudas’s family was traditionally devoted to Vitthala. He says:</p>
      <p className={pClass}>Amuchiye kuli pandhari nema Mukhi sada nama vithobache.</p>
      <p className={pClass}>In our family there is a tradition of vari to Pandharpur and (we) always repeat the name of Vithoba.</p>
      <p className={pClass}>Eknath was the great-grandson of Bhanudas. He performed rigorous sadhana for twelve years under the watchful eyes of his guru Janardana Swami. His life was the perfect synthesis of prapancha (dutiful householder life) and paramartha (spirituality). He supported the Varkari sampradaya through his witty kirtans, bhajans, vari, and religious celebrations and literature. He performed Hari-kirtan everyday in the Vitthala temple at Paithan. He was a scholar of the Sanskrit language and philosophy. His erudition and mastery of Sanskrit and Indian philosophical traditions is reflected throughout his literary compositions. Though highly influenced by the Advaita philosophy, he loved the sweetness of bhakti and the recitation of God’s name. Though a grihastha, he was the very incarnation of shanta-brahma (the calm of Brahman)! That is why his words reach the hearts of its readers instantaneously. Eknath wrote a commentary in ovi verse on the eleventh chapter of the Bhagavata. The orthodox brahmanas of Paithan were displeased with him because the commentary was in Prakrit. So Eknath took his writing to Kashi. The pandits of Kashi were delighted to see the embellished but devotional masterpiece, akshara-sampada. They encouraged him to write more and he composed another five chapters in Kashi. His work was completed on the Manikarnika Ghat and was honoured with a pompous procession. In a way, this was a great laudation for the entire Varkari sampradaya.</p>
      <p className={pClass}>Other works of Eknath include the Bhavartha Ramayana, Rukmini-swayamvara, commentary on the Chatuhshloki Bhagavata, Swatmasukha, Anandalahari, Hastamalaka, and Shukashtaka. Today we can read the Jnaneshwari in its pure form only because of the laborious efforts that Eknath put in to bring out a standard edition, rid of the corruptions that had crept in through oral traditions. The bharudas of Eknath have special place in Marathi literature. These are metaphorical verses which expound morality and religion through commonplace themes. Deities like Khandoba, Jokhai, and Yallamma; birds and animals—lapwing, ox, dog, and ram; children’s games—tipri (played with pieces of sticks) and eki-beki (a number game); household chores—grinding and pounding; and family relations: all figure in these bharudas. Eknath was perfectly sensitive to the social system and honestly tried to correct misinterpretation of religious tenets. He criticized the violence done in the name of religious sacrifices, bali. Spirituality was actively expressed in his life. His emptying his kawad (water jars) full of the holy Godavari waters into the mouth of an ass dying of thirst; his feeding of untouchables on the occasion of the Shraddha ceremony; his calm when spat upon repeatedly by a vindictive Muslim as he was returning from his bath; his bringing up of an untouchable boy; his spiritual ministrations to a concubine, to a prostitute, and to a criminal who had fled from jail; his patience with his arrogant son—all illustrate his social awareness and courage to act out his convictions. He also had a firm belief in the Advaita philosophy. His life is an excellent illustration of kriyashila jnana, knowledge expressed in action.</p>
      <p className={pClass}>A story is traditionally narrated about the fond relationship between Eknath and Jnaneshwar. Eknath was suffering from an affliction in his throat when Jnaneshwar appeared to him in a dream and told him that he would be cured if he removed the root of the Ajana tree that was encircling his (Jnaneshwar’s) neck in his samadhi-pitha at Alandi. Eknath did likewise and was not only cured but was also inspired to bring out a corrected edition of Jnaneshwari. Eknath tried to reach out to the simple, illiterate masses with the message of the Varkari sampradaya. He says:</p>
      <p className={pClass}>Kara kara lagpatha Dhara pandharichi vata; Pundalikachi peth Sopi ahe sarvansi.</p>
      <p className={pClass}>Be consistent and hold on to the path of Pandhari. The peth (abode or way) of Pundalika is simple and easy for all.</p>

      <h3 className={h3Class}>The Period of Tukaram (1608–49)</h3>
      <p className={pClass}>Tukaram was born at Dehu, fifteen miles from Pune. Tukaram’s life is a mix of intense joys and sorrows. His family was devoted to Vitthala for eight generations. But they suffered from harsh famine; his wife and son died and he became bankrupt. Tormented by difficulties in household life, death of dear ones, and jealous neighbours, his lot was one of agony and hardships. ‘I am always warring,’ he says, ‘with the world and with the mind. Accidents befall me all of a sudden and I try to ward them off by the power of Thy name.’ Despite his suffering, Tukaram is straightforward, upright, firm, and direct in his thoughts as is seen from his abhangas.</p>
      <p className={pClass}>The ‘dark night’ of Tukaram’s soul finally ended with the vision of God: ‘I see God’s face, and the vision gives me infinite bliss. My mind is riveted on it, and my hands cling to His feet.’ His deep identification with the Deity gives him a missionary zeal: ‘I enjoy this sweet ambrosia and distribute it among men. Do not wander among the woods. Come here and partake of my offer. Your desires shall be fulfilled, if your intellect is fastened to His feet. I come as a messenger from Vitthala.’</p>
      <p className={pClass}>Just like Eknath before him, Tukaram chose the medium of kirtan to spread the message of knowledge and devotion. Brahmanas like Rameshwara Bhatta, who opposed him initially, came to love his kirtans. Shivaji was also highly impressed by his kirtans. Tukaram never advised people to run away from their duties. He said that everyone should do their duties to perfection, but one must always be aware of one’s own spiritual essence. He was of the opinion that being spiritual did not mean being impractical. He says:</p>
      <p className={pClass}>Jodoniya dhana uttama vyavahare Udasa vichare vecah kari.</p>
      <p className={pClass}>Wealth is to be accumulated through immaculate conduct; and spent with the feeling of detachment.</p>
      <p className={pClass}>Again, ‘Nasave oshal, maga maniti sakala; do not be burdened by unnecessary obligations, then will all respect you.’</p>
      <p className={pClass}>Saint Tukaram spent his whole life spreading the teachings of the Varkari sampradaya. He harshly criticized the hypocrisy and malpractices current in society. His disciple Nilobaraya also composed many abhangas and was widely-known for his devotional singing.</p>

      <h3 className={h3Class}>The Period after Tukaram</h3>
      <p className={pClass}>An array of saints and holy persons have continued to be associated with the Varkari tradition, though they are not as well known as those mentioned above. They have continued to sincerely work for the uplift of the masses. A group (phada) of Mallappa Vaskar was one of the prominent groups in the post-Tukaram era.</p>

      <h2 className={h2Class}>Contributions of the Varkari Sampradaya</h2>
      <p className={pClass}>All the saints of the Varkari sampradaya were against dry, futile karma-kanda—ritual and idle talk. They tried to emphasize the true spiritual and humanistic essence of religion. They presented dharma in a simple, straightforward, and practical form. They emphatically propounded the religion of love and fraternity. Though profound scholars themselves, they decried sapless scholarship which failed to sense the nearness of God. They stressed the cultivation of an affectionate and loving heart.</p>
      <p className={pClass}>The work of these saints had great social importance, for they were great reformers. They did not have sectarian views or a shallow spirit. They lived the philosophy they taught. They provided the common men and women with the courage to aspire after brahma-jnana, the knowledge of Brahman. They said that every being—not the monk alone— is capable of getting moksha. The doors of Ishwara are open to all. They pointed out that ‘celibacy is not just the avoidance of the company of women; navhe brahmacharya bailichya tyage’; the feeling of non-attachment should be deep-rooted and natural.</p>
      <p className={pClass}>The literature of the Varkari sampradaya is a treasure of the Marathi language. Some of the saints speak in tones that are delicate and tender, like the rays of the moon, while others speak with the fierceness of fire. The breadth of their vision has remained highly inspiring.</p>
    </div>
  );
}
